server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/mail_sync_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Root@123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.auto=update

mail.accounts[0].host=imap.gmail.com
mail.accounts[0].port=993
mail.accounts[0].username=gunnitttt@gmail.com
mail.accounts[0].password=nwpv xtqi mkhm qphk
mail.accounts[0].protocol=imaps