spring.application.name=mail-sync-service

spring.datasource.url=jdbc:mysql://localhost:3306/mail_sync_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=test@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#spring.datasource.url=jdbc:sqlserver://10.48.12.180:14330;databaseName=SBI_IResolve;encrypt=false;trustServerCertificate=true;MultiSubnetFailover=true;ApplicationIntent=ReadWrite
#spring.datasource.username=Dems_Email
#spring.datasource.password=Dems_Email@123
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

logging.level.MAIL_SYNC_SERVICE_SBI=INFO
logging.level.com.sun.mail=WARN

server.port=8082
#server.address=SBIVADAACCUAT.tpsbi.com
#server.servlet.context-path=/mailService

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Inbox 1
#mail.accounts[0].host=imap.gmail.com
#mail.accounts[0].port=993
#mail.accounts[0].username=gunnitttt@gmail.com
#mail.accounts[0].password=nwpv xtqi mkhm qphk
#mail.accounts[0].protocol=imaps

# Inbox 1
mail.accounts[1].host=outlook.office365.com
mail.accounts[1].port=995
mail.accounts[1].username=Azmath.Patel@TeleperformanceDIBS.com
mail.accounts[1].password=Tech@123456789
mail.accounts[1].protocol=pop3s

# Inbox 2
#mail.accounts[1].host=10.191.145.88
#mail.accounts[1].port=995
#mail.accounts[1].username=sales@sbi.co.in
#mail.accounts[1].password=yourPassword2
#mail.accounts[1].protocol=pop3s

# Inbox 2
#mail.accounts[2].host=10.191.145.88
#mail.accounts[2].port=995
#mail.accounts[1].username=sales@sbi.co.in
#mail.accounts[1].password=yourPassword2
#mail.accounts[1].protocol=pop3s

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
logging.level.org.springframework.ws.client.MessageTracing.sent=TRACE
logging.level.org.springframework.ws.client.MessageTracing.received=TRACE

scheduler.end-script.enabled=false
swagger.url=http://localhost:8081/swagger-ui/index.html