server.port=8081
server.address=SBIVADAACCUAT.tpsbi.com

spring.datasource.url=jdbc:sqlserver://10.48.12.180:14330;databaseName=SBI_IResolve;encrypt=false;trustServerCertificate=true;MultiSubnetFailover=true;ApplicationIntent=ReadWrite
spring.datasource.username=Dems_Email
spring.datasource.password=Dems_Email@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

#mail.accounts[0].host=10.200.152.57
#mail.accounts[0].port=995
#mail.accounts[0].username=ganesh.ganesh14@Teleperformancedibs.com
#mail.accounts[0].password=Bank@123456789
#mail.accounts[0].protocol=pop3s