spring.application.name=mail-sync-service
spring.profiles.active=uat

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

logging.level.MAIL_SYNC_SERVICE_SBI=INFO
logging.level.com.sun.mail=WARN

#server.servlet.context-path=/mailService

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
logging.level.org.springframework.ws.client.MessageTracing.sent=TRACE
logging.level.org.springframework.ws.client.MessageTracing.received=TRACE

scheduler.end-script.enabled=false
swagger.url=http://localhost:8081/swagger-ui/index.html